name: Deploy to CloudHub with Maven
on:
  push:
    branches: [ "main" ]
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out code Repo 
      uses: actions/checkout@v3       
    - name: Build and deploy with Maven
      run: mvn clean deploy -DmuleDeploy -B -s .maven/settings.xml
      env:
        PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
        PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}       
